service:
  port: 8888

db:
  dsn: 'root:root@(127.0.0.1:3306)/test?charset=utf8&parseTime=True&loc=Local'

consul:
  address: '192.168.0.167:8500'
  name: 'try-go-service'
  localAddress: '127.0.0.1'
  localPort: 8888
  checkUrl: '/health'

